spring:
  application:
    name: orders-service

  # DataSource (PostgreSQL)
  datasource:
    url: jdbc:postgresql://localhost:5432/order_service_db
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver

  # JPA / Hibernate
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

  # Kafka  ← ici ! plus d’espace devant « kafka »
  kafka:
    bootstrap-servers: localhost:9092
    topics:
      order-placed: order.placed
      order-confirmed: order.confirmed
      order-failed: order.failed
      stock-reserved: stock.reserved
      stock-rejected: stock.rejected
    properties:
      schema.registry.url: http://localhost:8081

logging:
  level:
    org.springframework.boot.autoconfigure.jdbc: DEBUG

# Catalog service
catalog:
  service:
    url: http://localhost:8085
